src/Xero.php
The return type for getAccessToken() method needs to be string.
=> fix: DocBlock return type for getAccessToken()

src/Xero.php
To allow uploading of attachments, Xero API requires that a POST request send the raw data in the body (see https://developer.xero.com/documentation/api/accounting/attachments#post-attachments)
=> feat: enable to send raw body in request

src/Console/Commands/XeroKeepAliveCommand.php, src/Xero.php
This just now fetches all tenants to run a refresh, in theory if one person is using multiple tenants we could just use the same tokens but this approach covers all use cases and is the easiest method.
=> Update keep-alive for multi-tenant use, and storeToken where id when using tenant_id in the class

readme.md
I think this might be a copy/paste error in the readme as the description is for get invoice and relevant where clauses but the code was `Xero::contacts()`
=> Update readme.md instances of contacts to invoice

src/Models/XeroToken.php, src/Xero.php
Instead of guzzle allow the package to use Laravels Http Wrapper,  (laravel 8 & 9) 
this is tidier and allows for easier mocking in application based testing.
Additionally changed time to now to allow` Carbon::setTestNow(` to affect the expiry time
eg:
```
$inv = json_decode(file_get_contents(__DIR__ . '/../Snapshots/Xero/AddInvoice.json'), true);
$http = Http::fake([
'*' => Http::response($inv, 200),
]);
// call function that sends invoice to Xero
$calls = $http->recorded()->map(fn($call): array => json_decode($call[0]->body(), true));
$this->assertCount(1, $calls);
$first = $calls->first();
$this->assertIsArray($first);
$this->assertSame('ACCPAY', $first['Type']);
$this->assertSame(5, $first['LineItems'][0]['UnitAmount']);
$this->assertSame('uuid-9000', $first['Contact']['ContactID']); …
```
=> WIP: feat: upgrade to use Laravel Http wrapper for testability / mocking

readme.md, src/Xero.php
@dcblogdev 
PR #20 had a `dump()` call on the HTTP response, this removes it to prevent printing to stdout on each http call.
I also added the featured I mentioned in #20.
```php
$resp = Xero::get("invoices/{$invoiceId}", $data = null, $raw = true, $accept = 'application/pdf');
$pdfInvoiceString = $resp['body'];
```
This should be backwards compatible. I can seperate these two commits into seperate PRs if you'd prefer.
=> Add support for configurable Accept header in HTTP call 

src/Xero.php
To understand current issue here is how to reproduce it.
- Connect To xero
- Disconnect
- Connect again so that your record has id > 1
- try calling xero api after the token expiry which is around 30 minutes
- Now because current code check the xero tenant id agains id (primary key) column renewing token falls back to id =1 condition and adds new token on the db
- If you disconnect once, the packgage will still think xero is connected because of the first one is still remaining
-  Also i don't know why no one has found out, if you are connecting with multiple tenants no matter what, only first token is being used.
=> Critical Bugfix where tenant_id was checked against id column 

src/Xero.php
Useful for applying modified header for invoices, eventually will update the invoices method to include it there too.
=> Add header support to __call and __guzzle

src/Models/XeroToken.php
Our app has Laravel set up to use `CarbonImmutable`.
```php
Date::use(CarbonImmutable::class);
```
Because of this, `updated_at` is a `CarbonImmutable` instance which causes a type error when retrieving the `expires` attribute. This PR updates the return type to a more generic `DateTimeInterface`.
=> Use DateTimeInterface for Xero token expires attribute

config/xero.php, readme.md, src/Console/Commands/XeroShowAllCommand.php, src/Facades/Xero.php, src/Xero.php, src/database/migrations/create_xero_tokens_table.php, tests/XeroTest.php
Small code tidy up (Thanks to Pint) and enable encryption of tokens in the DB Level.
Note, not yet tested fully. Please run your standard tests :-) 
Existing tokens will need wiping as the Crypt class falls over if it doesn't match a Crypt store.
=> Add token encryption capabilties 

src/Xero.php, src/database/migrations/2024_03_15_135030_increase_xero_token_tables_string_length.php
Change refresh_token column type to text for support of the encryption method.
Ensure token exists before trying to get parts of it.
=> Encryption Improvements and Token Check

src/Facades/Xero.php, src/Resources/Contacts.php, src/Resources/Invoices.php, src/Resources/Webhooks.php
I believe your resource classes should extend the actual implementations, and not the facades - they are not themselves facades. To make this work you then have to call instance methods instead of calling back to the facade.
The original way makes phpstan upset in some situations, and mockery is unable to mock the objects using demeter chains due to all of the calls within each resource that then go back round through the facade.
Tests still pass etc, seems functionally equivalent - just more correct ? But perhaps that is subjective... 
Also added the docblocks to make phpstan happy(er).
=> Correct class inheritance for easier mockery usage

src/Enums/FilterOptions.php, src/Resources/Contacts.php, src/Resources/Invoices.php, src/Xero.php, tests/Enums/FilterOptionsTest.php, tests/Resources/ContactsTest.php, tests/Resources/InvoicesTest.php
This PR changes filtering from:
```php
Xero::contacts()->get(int $page = 1, string $where = null)
```
to fluent methods:
->filter() methods are optional and can add multiple filters. Only filters set out in an emum are supported:
```php
case IDS = 'ids';
case INCLUDEARCHIVED = 'includeArchived';
case ORDER = 'order';
case PAGE = 'page';
case SEARCHTERM = 'searchTerm';
case SUMMARYONLY = 'summaryOnly';
case WHERE = 'where';
```
```php
Xero::contacts()
->filter('page', 1)
->filter('where', 'EmailAddress=="info@abfl.com"')
->filter('where', 'ContactID==Guid("74ea95ea-6e1e-435d-9c30-0dff8ae1bd80")')
->filter('searchTerm', 'info')
->filter('includeArchived', 'false')
->filter('order', 'name')
->filter('summaryOnly', 'true')
->get();
```
=> Changed filters to by fluent rather than array based

src/Models/XeroToken.php
Added Eloquent attribute casting in the model to address the TypeError on the php artisan xero:keep-alive command. I have proposed this solution over a migration on the xero-tokens database to minimise the impact of the fix.
=> TypeError on Keep Alive artisan command

src/Resources/CreditNotes.php, src/Xero.php, tests/Resources/CreditNotesTest.php
A quick change to add support for querying credit notes.
=> Added Credit Note Support

src/Xero.php, tests/XeroTest.php
This pull request introduces a new `formatDate` method in the `Xero` class to handle date parsing and formatting, along with corresponding unit tests to ensure its functionality. It also includes updates to the imports for better exception handling.
* **Added `formatDate` method**: Introduced a method in `src/Xero.php` to parse and format date strings, supporting Microsoft JSON dates and ISO 8601 formats. The method throws exceptions for invalid inputs and handles timezone offsets.
* **Unit tests for `formatDate`**: Added tests in `tests/XeroTest.php` to validate the `formatDate` method's behavior with various input formats, including Microsoft JSON dates, ISO 8601 strings, and invalid inputs.
* **Updated imports**: Added `DateInvalidTimeZoneException`, `DateTime`, `DateTimeZone`, and …
=> Add formatDate method to handle date parsing and formatting

.github/workflows/php.yml
This pull request updates the PHP versions tested in the GitHub Actions workflow to include newer versions.
Updated the `php-versions` matrix to include PHP 8.3 and 8.4, replacing the previous version 8.2.
=> Update PHP versions in GitHub Actions to include 8.3 and 8.4

src/DTOs/ContactDTO.php, src/DTOs/InvoiceDTO.php, src/Enums/ContactStatus.php, src/Enums/FilterOptions.php, src/Enums/InvoiceLineAmountType.php, src/Enums/InvoiceStatus.php, src/Enums/InvoiceType.php, tests/DTOs/ContactDTOTest.php, tests/DTOs/InvoiceDTOTest.php, tests/Enums/ContactStatusTest.php, tests/Enums/InvoiceLineAmountTypeTest.php, tests/Enums/InvoiceStatusTest.php, tests/Enums/InvoiceTypeTest.php
This pull request introduces two new Data Transfer Objects (DTOs) for managing `Contact` and `Invoice` data, along with several supporting enums and test cases. The changes aim to enhance the structure, validation, and usability of the codebase for interacting with the Xero API.
* **`ContactDTO`**: Implements a structured representation of contact data, including methods for creating address, phone, and contact person arrays, and a `toArray` method for API compatibility.
* **`InvoiceDTO`**: Provides a structured representation of invoice data, including a method to create line items and a `toArray` method for API compatibility.
* **`ContactStatus`**: Defines valid statuses for a contact (`Active`, `Archived`, `GDPRRequest`) with a validation method.
* **`InvoiceLineAmountType`**: Defines …
=> Add DTOs and enums for Contact and Invoice management

src/Resources/Invoices.php, src/Xero.php
This pull request includes two changes aimed at improving code quality and functionality in the `Invoices` and `Xero` resources. The most important changes involve fixing a comment typo and updating the return type of a method to better reflect its behavior.
* Fixed a typo in a comment in the `attachment` method in `src/Resources/Invoices.php`. The word "fo" was corrected to "of" to improve clarity.
* Updated the return type of the `getTenantName` method in `src/Xero.php` from `string` to `?string` to allow for nullable values, aligning the method's behavior with its implementation.
=> Allow tenant name to be nullable in getTenantName method

src/Console/Commands/XeroShowAllTokensCommand.php, src/XeroServiceProvider.php, tests/Console/Commands/XeroShowAllTokensCommandTest.php
This pull request renames the `XeroShowAllCommand` to `XeroShowAllTokensCommand` across the codebase to better reflect its purpose. The changes include updates to the command signature, references in the service provider, and associated tests.
* Renamed the `XeroShowAllCommand` class to `XeroShowAllTokensCommand` and updated its signature from `xero:show-all` to `xero:show-all-tokens` in `src/Console/Commands/XeroShowAllTokensCommand.php`.
* Added the renamed `XeroShowAllTokensCommand` to the list of commands registered in the `XeroServiceProvider`. [[1]](diffhunk://#diff-8e9138868e0c65361bc3245de4fa53db80d38cdb32dfa8696987006b941f35a5R8) [[2]](diffhunk://#diff-8e9138868e0c65361bc3245de4fa53db80d38cdb32dfa8696987006b941f35a5R33)
* Updated the test file name from …
=> Add XeroShowAllTokensCommand and update service provider
